### ISSUE TITLE
Stratis software design document: Claim towards BTRFS without basis?!

### ISSUE THREAD

**Issue by ghost** [stratis-storage/stratis-storage.github.io#1]
According to this document
https://stratis-storage.github.io/StratisSoftwareDesign.pdf
At page 4 , section 1.2

It is claimed that BTRFS has significant technical issues that may never be resolved. 

Trying to validate that claim I can not find any basis for it (ref: https://www.mail-archive.com/linux-btrfs@vger.kernel.org/msg78114.html ).

Please update the document with either the relevant information or change the text to something more meaningful describing why BTRFS is unsuitable.

**Comment by agrover** [comment]
OK, probably better to just say "Btrfs has no licensing issues, but maintaining up-to-date-support for in it in enterprise kernels proved difficult."

**Comment by agrover** [comment]
fixed by https://github.com/stratis-storage/stratis-docs/pull/91
