### ISSUE TITLE
Website FAQ formatting is incorrect

### ISSUE THREAD

**Issue by jnsnow** [stratis-storage/stratis-storage.github.io#5]
https://github.com/stratis-storage/stratis-storage.github.io/blob/030d31a545f9f48ed02959b08b0aee756d27a21c/faq/index.html#L192

This was probably meant to be its own FAQ header. This document looks like it was generated from something like markdown; is the source for this document available to send PRs against? There are a few more issues in this FAQ page that I've spotted that could be adjusted.

**Comment by mulkieran** [comment]
Yes, you must be right. Please look in https://github.com/stratis-storage/stratis-docs/tree/master/content/static to find the original.

**Comment by mulkieran** [comment]
This may have been a zola bug, it looks correct in PR: https://github.com/stratis-storage/stratis-storage.github.io/pull/6, so I'll close.
